spring.application.name=welhire-cv-service
spring.datasource.url=jdbc:postgresql://localhost:5432/welhire-cv
spring.datasource.username=admin
spring.datasource.password=admin
# Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# -- Swagger / OpenAPI Config
swagger.title=CV Parsing API - WeHire
swagger.description=Microservice API for uploading and parsing resumes
swagger.version=1.0.0
swagger.contact.name=WeHire
swagger.contact.email=WeHire@example.com
swagger.contact.url=https://WeHire.com
swagger.license.name=MIT
swagger.license.url=https://opensource.org/licenses/MIT