spring.application.name=welhire-cv-service
spring.datasource.url=jdbc:postgresql://localhost:5432/welhire-cv
spring.datasource.username=admin
spring.datasource.password=admin
# Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect