spring.application.name=welhire-cv-service

# -- POSTGRES DB DETAILS
spring.datasource.url=jdbc:postgresql://localhost:5432/welhire-cv
spring.datasource.username=admin
spring.datasource.password=admin
# Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# -- MONGO DB DETAILS
spring.data.mongodb.uri=mongodb+srv://premchanduyerra:rC43x4rjojCHsCrz@cluster0.73lqagm.mongodb.net/welhire_2

# -- MICRO SERVICES
parsing.service.url=http://localhost:8082
candidate.service.url: http://localhost:8082


server.port=8082


# -- Swagger / OpenAPI Config
swagger.title=CV Parsing API - WeHire
swagger.description=Microservice API for uploading and parsing resumes
swagger.version=1.0.0
swagger.contact.name=WeHire
swagger.contact.email=WeHire@example.com
swagger.contact.url=https://WeHire.com
swagger.license.name=MIT
swagger.license.url=https://opensource.org/licenses/MIT

# -- CV UPLOADS PATH
cv.upload.base-path=C:/welhire/cv-uploads

# -- DEBUGGING
logging.level.com.welhire.cv.client.ParsingClient: DEBUG
logging.level.feign: DEBUG


# Async thread pool configuration
app.async.core-pool-size=1
app.async.max-pool-size=10
app.async.queue-capacity=50
app.async.thread-name-prefix=parse-






