spring.application.name=welhire-discovery
# Server runs on 8761 (standard Eureka port)
server.port=8761

# Do not register itself (this is the registry itself)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Optional: Define hostname for clean dashboard info
eureka.instance.hostname=localhost

